### ISSUE TITLE
Investigate OAuth backend integration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-kubernetes#202]
As a developer, I'd like to configure and integrate with the OAuth backend, so I can protect the SCDF's REST endpoints via OAuth authentication and authorization. 

**Acceptance:**
- Review and adapt to [SCDF's core OAuth](http://docs.spring.io/spring-cloud-dataflow/docs/1.2.2.RELEASE/reference/htmlsingle/#configuration-security-oauth2) support and the configurations
- Integration tests included
- Document best practices to run SCDF with OAuth on Kubernetes

**Comment by trisberg** [comment]
I'm wondering how we want to handle authorization for OAuth - if I set it up to authenticate with an OAuth server like Google's then anyone with a Gmail account can log in and use the service.

**Comment by trisberg** [comment]
To set up authentication using Google follow these instructions: https://developers.google.com/identity/sign-in/web/devconsole-project

Then add the following OAuth config for the server:

```
  security:
    oauth2:
      client:
        client-id: <Client ID>                                             
        client-secret: <Client secret>
        access-token-uri: https://www.googleapis.com/oauth2/v4/token
        user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
        scope: openid,email,profile
      resource:
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
```
