### ISSUE TITLE
skipper always restart

### ISSUE THREAD

**Issue by scne** [spring-cloud/spring-cloud-dataflow-server-kubernetes#333]
I try to configure my kubernetes cluseter with SCDF. I need to use skipper but this POD always restart 

```
.....
  Type     Reason                 Age               From                  Message
  ----     ------                 ----              ----                  -------
  Normal   Scheduled              2m                default-scheduler     Successfully assigned skipper-64c84f45b8-7p8b6 to claudiopomo
  Normal   SuccessfulMountVolume  2m                kubelet, claudiopomo  MountVolume.SetUp succeeded for volume "default-token-7jmbs"
  Warning  BackOff                34s               kubelet, claudiopomo  Back-off restarting failed container
  Normal   Pulling                20s (x3 over 2m)  kubelet, claudiopomo  pulling image "springcloud/spring-cloud-skipper-server:1.1.0.BUILD-SNAPSHOT"
  Normal   Pulled                 19s (x3 over 2m)  kubelet, claudiopomo  Successfully pulled image "springcloud/spring-cloud-skipper-server:1.1.0.BUILD-SNAPSHOT"
  Normal   Created                18s (x3 over 2m)  kubelet, claudiopomo  Created container
  Normal   Started                18s (x3 over 2m)  kubelet, claudiopomo  Started container
```

This is my configuration, I'm using kafka as message broker
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skipper
  labels:
    app: skipper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skipper
    spec:
      containers:
      - name: skipper
        image: springcloud/spring-cloud-skipper-server:1.1.0.BUILD-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 640Mi
        env:
        - name: SPRING_APPLICATION_JSON
          value: "{\"spring.cloud.skipper.server.enableLocalPlatform\" : false, \"spring.cloud.skipper.server.platform.kubernetes.accounts.minikube.environmentVariables\": \"SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT}, SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${KAFKA_ZK_SERVICE_HOST}:${KAFKA_ZK_SERVICE_PORT}, SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_BROKERS=${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT}, SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_ZK_NODES=${KAFKA_ZK_SERVICE_HOST}:${KAFKA_ZK_SERVICE_PORT}\",\"spring.cloud.skipper.server.platform.kubernetes.accounts.minikube.memory\" : \"1024Mi\",\"spring.cloud.skipper.server.platform.kubernetes.accounts.minikube.createDeployment\" : true}"
```
