### ISSUE TITLE
Helm liveness and readiness probe values not taking effect

### ISSUE THREAD

**Issue by allanmoso** [spring-cloud/spring-cloud-dataflow-server-kubernetes#364]
Using the default values in `values.yaml` file:
```yaml
deployer:
  resourceLimits:
    cpu: 500m
    memory: 1024Mi
  readinessProbe:
    initialDelaySeconds: 120
  livenessProbe:
    initialDelaySeconds: 90
```
The deployed application pods have different liveness and readiness values:
```
    Liveness:   http-get http://:8080/health delay=10s timeout=2s period=60s #success=1 #failure=3
    Readiness:  http-get http://:8080/info delay=10s timeout=2s period=10s #success=1 #failure=3
```
