### ISSUE TITLE
RBAC error accessing task logs

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-kubernetes#433]
Installed SCDF 2.2.0 using Helm chart v2.4.0 on GKE with k8s v1.13.7-gke.19. Created a Task and executed it using the UI. Trying to access the execution logs I get this error:

```
Failure executing: GET at: https://10.11.240.1/api/v1/namespaces/default/pods/mytask-nl8zr46yx4/log?pretty=false&tailLines=500. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "mytask-nl8zr46yx4" is forbidden: User "system:serviceaccount:default:scdf-data-flow" cannot get resource "pods/log" in API group "" in the namespace "default".
```

**Comment by trisberg** [comment]
Adding the following to the `role.rbac.authorization.k8s.io/scdf-data-flow` resource
 seems to help:

```
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
```
