### ISSUE TITLE
RabbitMQ console not accessible when hosted on Kubernetes (minikube for local dev)

### ISSUE THREAD

**Issue by Galileo1** [spring-cloud/spring-cloud-dataflow-server-kubernetes#435]
Hey, can any one please suggest how can I access the rabbitmq console. It is running as cluster-ip not as nodePort service so I believe it won't be accessible. Also I tried to port-forward this pod but cannot access the rabbitmq console.

If I see the doco for rabbitmq. It is exposed on another port 15672. Even to access that I need to change the service to be NodePort and also have another port(15672).

Can some please look into below deployment files and suggest the changes . I am not sure if using NodePort on svc will impact how server would access rabbitmq nessage broker?? 

![image](https://user-images.githubusercontent.com/9716232/83340887-7c28e000-a331-11ea-86f4-163abe06a093.png)

**Current Deployment:** 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.6.10
        name: rabbitmq
        ports:
        - containerPort: 5672
```

**Current Service** 
```
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq
```

--------------Change I think I should do -----------------

```
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: ui
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31112
    - name: service
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 31111
  selector:
    app: rabbitmq
  type: NodePort
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.6.10
        name: rabbitmq
-       containerPort: 5672
          name: http-port
          containerPort: 15672
          name: ui-port
```
